Convert the project to typescript and improve typescript
auth0/express-jwt pull request #274
Opened 2022-03-16 16:38 UTC by jfromaniello

### Description

This changes convert the project to typescript to address several issues with its current type definitions and make things easier for the user.

Example of two middlewares using expressjwt:

```typescript
import { expressjwt, ExperssJwtRequest } from "express-jwt";

app.get(
  "/protected",
  expressjwt({ secret: "shhhhhhared-secret", algorithms: ["HS256"] }),
  function (req: ExperssJwtRequest, res: express.Response) {
    if (!req.auth.admin) return res.sendStatus(401);
    res.sendStatus(200);
  }
);
```

It also simplify the interface a bit by conveying to a callback pattern of `request`, `token` and `callback` in the `isRevoked` and `secret` functions.

Removes also the feature of changing the output for the decoded token, `userProperty`, `requestProperty` and `resultProperty`. The middleware puts the decoded token always on `req.auth`.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

2022-03-16 16:57 UTC, shellscape reviewed
Thanks very much for putting this together. I have a few comments and suggestions, but nothing that would block this from moving forward.

2022-03-16 18:12 UTC, jfromaniello commented
@shellscape Excellent feedback, since we are breaking compatibility I changed everything to promises including the parameter functions.

2022-03-17 21:12 UTC, GfxKai requested changes
Came across this PR as I was trying to debug some typing issues—problem solved, thanks!! Just adding a review as I noticed a typo 🦞

2022-03-17 21:12 UTC, GfxKai commented on src/index.ts
> +      const request = req as ExperssJwtRequest<jwt.JwtPayload | string>;
```suggestion
      const request = req as ExpressJwtRequest<jwt.JwtPayload | string>;
```

2022-03-17 21:12 UTC, GfxKai commented on src/index.ts
> +export type ExperssJwtRequest<T = jwt.JwtPayload> =
```suggestion
export type ExpressJwtRequest<T = jwt.JwtPayload> =
```

2022-03-17 21:12 UTC, GfxKai commented on README.md
> +An `ExperssJwtRequest` type is provided which extends `express.Request` with the `auth` property.
```suggestion
An `ExpressJwtRequest` type is provided which extends `express.Request` with the `auth` property.
```

2022-03-17 21:12 UTC, GfxKai commented on README.md
> +// import { expressjwt, ExperssJwtRequest } from "express-jwt";
```suggestion
// import { expressjwt, ExpressJwtRequest } from "express-jwt";
```

2022-03-17 21:12 UTC, GfxKai commented on README.md
> +  function (req: ExperssJwtRequest, res: express.Response) {
```suggestion
  function (req: ExpressJwtRequest, res: express.Response) {
```

2022-03-17 21:12 UTC, GfxKai commented on test/jwt.test.ts
> +import { expressjwt, UnauthorizedError, ExperssJwtRequest, GetVerificationKey } from '../src';
```suggestion
import { expressjwt, UnauthorizedError, ExpressJwtRequest, GetVerificationKey } from '../src';
```

2022-03-17 21:12 UTC, GfxKai commented on test/jwt.test.ts
> +    const req = {} as ExperssJwtRequest;
```suggestion
    const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/jwt.test.ts
> +    const req = {} as ExperssJwtRequest;
```suggestion
    const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/jwt.test.ts
> +    const req = {} as ExperssJwtRequest;
```suggestion
    const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/jwt.test.ts
> +    const req = {} as ExperssJwtRequest;
```suggestion
    const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/multitenancy.test.ts
> +import { expressjwt, ExperssJwtRequest, GetVerificationKey } from '../src';
```suggestion
import { expressjwt, ExpressJwtRequest, GetVerificationKey } from '../src';
```

2022-03-17 21:12 UTC, GfxKai commented on test/multitenancy.test.ts
> +  const req = {} as ExperssJwtRequest;
```suggestion
  const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/revocation.test.ts
> +import { expressjwt, ExperssJwtRequest } from '../src';
```suggestion
import { expressjwt, ExpressJwtRequest } from '../src';
```

2022-03-17 21:12 UTC, GfxKai commented on test/revocation.test.ts
> +    const req = {} as ExperssJwtRequest;
```suggestion
    const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/revocation.test.ts
> +    const req = {} as ExperssJwtRequest;
```suggestion
    const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/revocation.test.ts
> +    const req = {} as ExperssJwtRequest;
```suggestion
    const req = {} as ExpressJwtRequest;
```

2022-03-17 21:12 UTC, GfxKai commented on test/string_token.test.ts
> +import { expressjwt, ExperssJwtRequest } from '../src';
```suggestion
import { expressjwt, ExpressJwtRequest } from '../src';
```

2022-03-17 21:12 UTC, GfxKai commented on test/string_token.test.ts
> +  const req = {} as ExperssJwtRequest<string>;
```suggestion
  const req = {} as ExpressJwtRequest<string>;
```

2022-03-17 21:12 UTC, GfxKai commented on README.md
> +import { expressjwt, ExperssJwtRequest } from "express-jwt";
```suggestion
import { expressjwt, ExpressJwtRequest } from "express-jwt";
```

2022-03-17 23:51 UTC, jfromaniello commented
Good catch @GfxKai ! Thank you very much ❤️

2022-04-04 19:14 UTC, shellscape commented
@jfromaniello I think we're good 🎉

2022-04-20 12:26 UTC, merged

2022-04-20 12:28 UTC, jfromaniello commented
I just released it as `v7.0.0`.